# Generated by Django 3.0.4 on 2020-04-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200405_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
