# Generated by Django 3.0.4 on 2020-04-05 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0004_auto_20200405_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.IntegerField(default=9372238858, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)], verbose_name='Mobile No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
